Bikes/Controllers/AdminBikeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Bikes.Models;

namespace Bikes.Controllers
{
    [Authorize(Roles ="Admin")]

    public class AdminBikeController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AdminBikeController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: AdminBike
        [HttpGet]
        public async Task<IActionResult> Index(int id)
        {
            if (_context.Bike == null)
            {
                return Problem("Entity set 'ApplicationDbCotext.Bike' is null");
            }
            var products = await _context.Bike.ToListAsync();
            foreach (var product in products)
            {
                product.BikeImages = _context.BikeImage.Where(pi => pi.BikeId == product.Id).ToList();
                product.BikeCategories = _context.BikeCategory.Where(pc => pc.BikeId == product.Id).ToList();
            }
            ViewBag.Categories = _context.Category.ToList();
            return View(products);
        }

        // GET: AdminBike/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Bike == null)
            {
                return NotFound();
            }

            var bike = await _context.Bike
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bike == null)
            {
                return NotFound();
            }

            return View(bike);
        }

        // GET: AdminBike/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: AdminBike/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Active,Quantity,Price")] Bike bike)
        {
            ModelState.Remove("BikeImages");
            ModelState.Remove("OrderItems");
            ModelState.Remove("BikeCategories");
            if (ModelState.IsValid)
            {
                _context.Add(bike);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(bike);
        }

        // GET: AdminBike/Edit/5
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Bike == null)
            {
                return NotFound();
            }

            var bike = await _context.Bike.FindAsync(id);
            if (bike == null)
            {
                return NotFound();
            }
            bike.BikeImages = _context.BikeImage.Where(pi => pi.BikeId == bike.Id).ToList();
            bike.BikeCategories = _context.BikeCategory.Where(pc => pc.BikeId == bike.Id).ToList();
            ViewBag.Categories = _context.Category.ToList();
            return View(bike);
        }

        // POST: AdminBike/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Active,Quantity,Price")] Bike bike)
        {
            if (id != bike.Id)
            {
                return NotFound();
            }
            ModelState.Remove("BikeImages");
            ModelState.Remove("OrderItems");
            ModelState.Remove("BikeCategories");
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bike);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BikeExists(bike.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(bike);
        }
 
        public async Task<IActionResult> EditCategory(int id)
        {
            List<Category> categories = _context.Category.ToList();
            foreach (var cat in categories)
            {
                    var checkbox = Request.Form[cat.Name];
                if (checkbox.Contains("true"))
                {
                    if (_context.BikeCategory.FirstOrDefault(x => x.CategoryId == cat.Id && x.BikeId == id) == null)
                        _context.BikeCategory.Add(new BikeCategory() { CategoryId = cat.Id, BikeId = id });
                }
                else
                {
                    var p = _context.BikeCategory.FirstOrDefault(x => x.CategoryId == cat.Id && x.BikeId == id);
                    if (p != null) _context.BikeCategory.Remove(p);
                }
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Edit), new { id });
        }
        public async Task<IActionResult> EditBike(int id)
        {
            List<Category> categories = _context.Category.ToList();
            foreach (var cat in categories)
            {
                var checkbox = Request.Form[cat.Name];
                if (checkbox.Contains("true"))
                {
                    if (_context.BikeCategory.FirstOrDefault(x => x.CategoryId == cat.Id && x.BikeId == id) == null)
                    {
                        _context.BikeCategory.Add(new BikeCategory() { CategoryId = cat.Id, BikeId = id });
                    }

                }
                else
                {
                    var p = _context.BikeCategory.FirstOrDefault(x => x.CategoryId == cat.Id && x.BikeId == id);

                    if (p != null)
                    {
                        _context.BikeCategory.Remove(p);
                    }
                }
            }
            _context.SaveChanges();
            return RedirectToAction(nameof(Edit), new { id });

        }
        // GET: AdminBike/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Bike == null)
            {
                return NotFound();
            }

            var bike = await _context.Bike
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bike == null)
            {
                return NotFound();
            }

            return View(bike);
        }

        // POST: AdminBike/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Bike == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Bike'  is null.");
            }
            var bike = await _context.Bike.FindAsync(id);
            if (bike != null)
            {
                _context.Bike.Remove(bike);
                _context.BikeImage.RemoveRange(_context.BikeImage.Where(pc => pc.BikeId == bike.Id));

            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BikeExists(int id)
        {
          return (_context.Bike?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Bikes/Controllers/CartController.cs
using Humanizer;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Bikes.Extensions;
using Bikes.Models;

namespace Movies2.Controllers
{
    public class CartController : Controller
    {
        public const string SessionKeyName = "_cart";
        private readonly ApplicationDbContext _context;

        public CartController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            List<CartItem> cart = HttpContext.Session.GetObjectFromJson<List<CartItem>>(SessionKeyName);
            //ako je cart null instanciramo ga.moramo osigurat i da se barem stvori prazna lista

            if (cart == null)
            {
                cart = new List<CartItem>();

            }
            decimal total = 0;
            foreach (CartItem item in cart)
            {
                item.Bike.BikeImages = _context.BikeImage.Where(pi => pi.BikeId == item.Bike.Id).ToList();
                total += item.GetTtotal();
            }
            ViewBag.CartTotal = total;
            return View(cart);
        }
        [HttpPost]

        public IActionResult AddToCart(int productId)
        {
            List<CartItem> cart = HttpContext.Session.GetObjectFromJson<List<CartItem>>(SessionKeyName);
            if (cart == null)
            {
                cart = new List<CartItem>();

            }
            if (cart.Count == 0)//Ukoliko je cart prazan
            {
                CartItem item = new CartItem()
                {
                    Bike = _context.Bike.Find(productId= 1)
                };
                cart.Add(item);
                HttpContext.Session.SetObjectAsJson(SessionKeyName, cart);
            }
            else//cart not  empty,so check if item already exists in cart
            {
                bool found = false;
                foreach (CartItem item in cart)
                {
                    if (item.Bike.Id == productId)
                    {
                        item.Quantity++;
                        found = true;
                        break;

                    }

                }
                if (!found)
                {
                    CartItem item = new CartItem()
                    {
                        Bike = _context.Bike.Find(productId),
                        Quantity = 1

                    };
                    cart.Add(item);
                }
                HttpContext.Session.SetObjectAsJson(SessionKeyName, cart);

            }
            return RedirectToAction("Index");
        }
        public IActionResult RemoveFromCart(int bikeId)
        {
            List<CartItem> cart = HttpContext.Session.GetObjectFromJson<List<CartItem>>(SessionKeyName);

            cart.RemoveAll(item => item.Bike.Id == bikeId);

            HttpContext.Session.SetObjectAsJson(SessionKeyName, cart);

            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult ChangeCartItemQuantity(int productId, decimal quantity)
        {
            if (quantity <= 0)
            {
                return RedirectToAction("RemoveFromCart", new { productId = productId });

            }
            List<CartItem> cart = HttpContext.Session.GetObjectFromJson<List<CartItem>>(SessionKeyName);
            foreach (CartItem item in cart)
            {
                if (item.Bike.Id == productId)
                {
                    item.Quantity = quantity;
                    break;

                }

            }
            HttpContext.Session.SetObjectAsJson(SessionKeyName, cart);
            return RedirectToAction("Index");

        }
    }
}

Bikes/Controllers/UserController.cs
using Bikes.Models;
using Bikes.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SQLitePCL;

namespace Bikes.Controllers
{
    public class UserController:Controller
    {
        
        
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        public UserController(
            ApplicationDbContext context,
            UserManager<ApplicationUser> userManager)
        {
            
            _context = context;
            _userManager = userManager;

        }


        public IActionResult Index()
        {
            var users = _context.Users.ToList();
            var userRoles = _context.UserRoles.ToList();
            var roles = _context.Roles.ToList();
            foreach (var user in users)
            {
                var roleId = userRoles.FirstOrDefault(u => u.UserId == user.Id).RoleId;
                user.Role = roles.FirstOrDefault(u => u.Id == roleId).Name;

            }
            return View(users);
        }

        public IActionResult RoleManagment(string id)
        { 
            

            string RoleID =_context.UserRoles.FirstOrDefault(u => u.UserId ==id).RoleId;
           
            RoleManagmentVM Roleman = new RoleManagmentVM()
            {
                ApplicationUser = _context.Users.FirstOrDefault(u => u.Id == id),
                RoleList = _context.Roles.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Name
                })
            };
            
            Roleman.ApplicationUser.Role = _context.Roles.FirstOrDefault(u => u.Id == RoleID).Name;
          

            return View(Roleman);
        }
        [HttpPost]

        public IActionResult RoleManagment(RoleManagmentVM roleManagmentVM)
        {
            string RoleID = _context.UserRoles.FirstOrDefault(u => u.UserId == roleManagmentVM.ApplicationUser.Id).RoleId;
            string oldRole = _context.Roles.FirstOrDefault(u => u.Id == RoleID).Name;
            if (!(roleManagmentVM.ApplicationUser.Role == oldRole))
            {
                ApplicationUser applicationUser = _context.Users.FirstOrDefault(u => u.Id == roleManagmentVM.ApplicationUser.Id);
                _context.SaveChanges();
                _userManager.RemoveFromRoleAsync(applicationUser, oldRole).GetAwaiter().GetResult();
                _userManager.AddToRoleAsync(applicationUser, roleManagmentVM.ApplicationUser.Role).GetAwaiter().GetResult();
            }
            
            return RedirectToAction("Index");
        }
        public IActionResult Delete(string id)
        {
          
            var user =   _context.Users.FirstOrDefault(m => m.Id == id);
            if (user != null)
            {
                 _context.Remove(user);
            

            }
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        
    }
}

Bikes/Views/Shared/_AdminMenuPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Bikes.Models;
@using Bikes.ViewModels
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

 @if (SignInManager.IsSignedIn(User) && await UserManager.IsInRoleAsync(UserManager.GetUserAsync(User).Result, "Admin"))
{ 
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Admin</a>
        <div class="dropdown-menu">

            <a class="dropdown-item" asp-action="Index" asp-controller="AdminCategory">Categories</a>
            <a class="dropdown-item" asp-action="Index" asp-controller="AdminBike">Bikes</a>

            <div class="dropdown-divider"></div>
            <a class="dropdown-item" asp-action="Index" asp-controller="AdminOrder">Orders</a>

        <a class="nav-link text-dark" asp-controller="User" asp-action="Index">User controller</a>

        </div>
    </li>
}
 

Bikes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bikes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Bikes.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
           @*      <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bikes</a> *@
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <partial name="_PublicMenuPartial" />

                      
                        <partial name="_AdminMenuPartial" />
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Bikes - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Bikes/Views/Shared/_OrderItemsPartial.cshtml
@model List<OrderItem>

<table class="table">
    <thead>
    <th>
        Product
    </th>
    <th>
        Quantity

    </th>
    <th>
        Price
    </th>
    <th>
        Total
    </th>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem=>item.BikeName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem=>item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem=>item.Price)

                </td>
                <td>
                    @((item.Price * item.Quantity).ToString("0.00")) €
                </td>
            </tr>
        }
    </tbody>
</table>

Bikes/Views/Shared/_PublicMenuPartial.cshtml
@using Microsoft.AspNetCore.Http;
@using Bikes.Extensions;
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor;


<li class="nav-item">
    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Bike" asp-route-id="">Bikes</a>
</li>
<li class="nav-item">
    @{
        var cart = HttpContextAccessor.HttpContext.Session.GetObjectFromJson<List<Bikes.Extensions.CartItem>>("_cart");
        int broj = 0;
        if (cart != null)
        {
            broj = cart.Count();
        }
        string ispis = " Cart ";
        if (broj > 0)
        {
            ispis += " ( " + broj + " ) ";
        }
    }
    <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">

        @ispis
    </a>
</li>