Bikes/Controllers/AdminBikeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Bikes.Models;

namespace Bikes.Controllers
{
    [Authorize(Roles ="Admin")]

    public class AdminBikeController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AdminBikeController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: AdminBike
        [HttpGet]
        public async Task<IActionResult> Index(int id)
        {
            if (_context.Bike == null)
            {
                return Problem("Entity set 'ApplicationDbCotext.Bike' is null");
            }
            var products = await _context.Bike.ToListAsync();
            foreach (var product in products)
            {
                product.BikeImages = _context.BikeImage.Where(pi => pi.BikeId == product.Id).ToList();
                product.BikeCategories = _context.BikeCategory.Where(pc => pc.BikeId == product.Id).ToList();
            }
            ViewBag.Categories = _context.Category.ToList();
            return View(products);
        }

        // GET: AdminBike/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Bike == null)
            {
                return NotFound();
            }

            var bike = await _context.Bike
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bike == null)
            {
                return NotFound();
            }

            return View(bike);
        }

        // GET: AdminBike/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: AdminBike/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Active,Quantity,Price")] Bike bike)
        {
            ModelState.Remove("BikeImages");
            ModelState.Remove("OrderItems");
            ModelState.Remove("BikeCategories");
            if (ModelState.IsValid)
            {
                _context.Add(bike);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(bike);
        }

        // GET: AdminBike/Edit/5
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Bike == null)
            {
                return NotFound();
            }

            var bike = await _context.Bike.FindAsync(id);
            if (bike == null)
            {
                return NotFound();
            }
            bike.BikeImages = _context.BikeImage.Where(pi => pi.BikeId == bike.Id).ToList();
            bike.BikeCategories = _context.BikeCategory.Where(pc => pc.BikeId == bike.Id).ToList();
            ViewBag.Categories = _context.Category.ToList();
            return View(bike);
        }

        // POST: AdminBike/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Active,Quantity,Price")] Bike bike)
        {
            if (id != bike.Id)
            {
                return NotFound();
            }
            ModelState.Remove("BikeImages");
            ModelState.Remove("OrderItems");
            ModelState.Remove("BikeCategories");
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bike);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BikeExists(bike.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(bike);
        }
 
        public async Task<IActionResult> EditCategory(int id)
        {
            List<Category> categories = _context.Category.ToList();
            foreach (var cat in categories)
            {
                    var checkbox = Request.Form[cat.Name];
                if (checkbox.Contains("true"))
                {
                    if (_context.BikeCategory.FirstOrDefault(x => x.CategoryId == cat.Id && x.BikeId == id) == null)
                        _context.BikeCategory.Add(new BikeCategory() { CategoryId = cat.Id, BikeId = id });
                }
                else
                {
                    var p = _context.BikeCategory.FirstOrDefault(x => x.CategoryId == cat.Id && x.BikeId == id);
                    if (p != null) _context.BikeCategory.Remove(p);
                }
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Edit), new { id });
        }
        public async Task<IActionResult> EditBike(int id)
        {
            List<Category> categories = _context.Category.ToList();
            foreach (var cat in categories)
            {
                var checkbox = Request.Form[cat.Name];
                if (checkbox.Contains("true"))
                {
                    if (_context.BikeCategory.FirstOrDefault(x => x.CategoryId == cat.Id && x.BikeId == id) == null)
                    {
                        _context.BikeCategory.Add(new BikeCategory() { CategoryId = cat.Id, BikeId = id });
                    }

                }
                else
                {
                    var p = _context.BikeCategory.FirstOrDefault(x => x.CategoryId == cat.Id && x.BikeId == id);

                    if (p != null)
                    {
                        _context.BikeCategory.Remove(p);
                    }
                }
            }
            _context.SaveChanges();
            return RedirectToAction(nameof(Edit), new { id });

        }
        // GET: AdminBike/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Bike == null)
            {
                return NotFound();
            }

            var bike = await _context.Bike
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bike == null)
            {
                return NotFound();
            }

            return View(bike);
        }

        // POST: AdminBike/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Bike == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Bike'  is null.");
            }
            var bike = await _context.Bike.FindAsync(id);
            if (bike != null)
            {
                _context.Bike.Remove(bike);
                _context.BikeImage.RemoveRange(_context.BikeImage.Where(pc => pc.BikeId == bike.Id));

            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BikeExists(int id)
        {
          return (_context.Bike?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Bikes/Controllers/AdminBikeImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using System.IO;
using Bikes.Models;

namespace Bikes.Controllers
{
    [Authorize(Roles ="Admin")]
    public class AdminBikeImageController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AdminBikeImageController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: AdminBikeImage
        public async Task<IActionResult> Index(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index","AdminBike");
            }
            ViewBag.BikeId = id;
            return _context.BikeImage != null ?
                        View(await _context.BikeImage.Where(x => x.BikeId == id).ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.BikeImage'  is null.");
        }

        // GET: AdminBikeImage/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.BikeImage == null)
            {
                return NotFound();
            }

            var bikeImage = await _context.BikeImage
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bikeImage == null)
            {
                return NotFound();
            }

            return View(bikeImage);
        }

        // GET: AdminBikeImage/Create
        public IActionResult Create(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "AdminBike");

            }
            if (_context.Bike.Count(p => p.Id == id) == 0)
            {
                return RedirectToAction("Index", "AdminBike");
            }
            return View(new BikeImage() { BikeId = (int)id });
        }

        // POST: AdminBikeImage/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
      // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,BikeId,IsMainImage,Name,FileName")] BikeImage bikeImage)
        {
            ModelState.Remove("BikeName");
            if (HttpContext.Request.Form.Files.Count > 0)
            {
                ModelState.Remove("FileName");
            }
            if (ModelState.IsValid)
            {


                var imageFile = HttpContext.Request.Form.Files.FirstOrDefault();

                var uploadPath = System.IO.Path.Combine("wwwroot", "images", "products", bikeImage.BikeId.ToString());
                if (!System.IO.Directory.Exists(uploadPath))
                {
                    System.IO.Directory.CreateDirectory(uploadPath);

                }
                if (imageFile != null)
                {
                    var fileName = System.IO.Path.Combine(uploadPath, imageFile.FileName);
                    using (var fileStream = new System.IO.FileStream(fileName, System.IO.FileMode.Create))
                    {
                        await imageFile.CopyToAsync(fileStream);

                    }
                    fileName = fileName.Replace("wwwroot\\", "/").Replace("\\", "/");
                    bikeImage.FileName = fileName;
                }
                bikeImage.Id = 0;
                _context.Add(bikeImage);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { id = bikeImage.BikeId });
            }
            return View(bikeImage);
        }

        // GET: AdminBikeImage/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.BikeImage == null)
            {
                return NotFound();
            }

            var bikeImage = await _context.BikeImage.FindAsync(id);
            if (bikeImage == null)
            {
                return NotFound();
            }
            return View(bikeImage);
        }

        // POST: AdminBikeImage/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,BikeId,IsMainImage,Name,FileName")] BikeImage bikeImage)
        {
            if (id != bikeImage.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bikeImage);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BikeImageExists(bikeImage.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(bikeImage);
        }

        // GET: AdminBikeImage/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.BikeImage == null)
            {
                return NotFound();
            }

            var bikeImage = await _context.BikeImage
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bikeImage == null)
            {
                return NotFound();
            }

            return View(bikeImage);
        }

        // POST: AdminBikeImage/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.BikeImage == null)
            {
                return Problem("Entity set 'ApplicationDbContext.BikeImage'  is null.");
            }
            var bikeImage = await _context.BikeImage.FindAsync(id);
            if (bikeImage != null)
            {
                var fileName = "wwwroot" + bikeImage.FileName.Replace("/", "\\");
                System.IO.File.Delete(fileName);
                _context.BikeImage.Remove(bikeImage);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { id = bikeImage.BikeId });
        }

        private bool BikeImageExists(int id)
        {
          return (_context.BikeImage?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Bikes/Views/AdminBike/Create.cshtml
@model Bike

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Bike</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" ></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input type="number" asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Bikes/Views/AdminBike/Delete.cshtml
@model Bike

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Bike</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Active)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Bikes/Views/AdminBike/Details.cshtml
@model Bike

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Bike</h4>
    <div class="row">
        @if (Model.BikeImages != null)
        {
            foreach (var image in Model.BikeImages)
            {
                <div class="col-sm-3">
                    <img src="@image.FileName" alt="@Model.Name" height="100" />
                </div>
            }
        }
        else
        {

            <div class="col-sm-3">
                <img src="~/images/noimage.jpg" alt="@Model.Name" height="100" />
            </div>

        }
    </div>
    <hr />
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Active)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Bikes/Views/AdminBike/Edit.cshtml
@model Bikes.Models.Bike

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Bike</h4>
<hr />
<div class="row">
    @if (Model.BikeImages != null)
    {
        foreach (var image in Model.BikeImages)
        {
            <div class="col-sm-3">
                <img src="@image.FileName" alt="@Model.Name" height="100" />
            </div>
        }
    }
    else
    {
        <div class="col-sm-3">
            <img src="~/images/noimage.png" alt="@Model.Name" height="100" />
        </div>
    }
</div>
<a asp-controller="AdminBikeImage" asp-action="Index" asp-route-id="@Model.Id">Edit images</a>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" > </textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input class="btn btn-primary"  type="submit" value="Save" />
            </div>
        </form>
    </div>
    <div class="col-md-4">
        <form asp-action="EditCategory">
            <input type="hidden" asp-for="Id" />
            <label>Categories</label>
            @foreach (Category cat in ViewBag.Categories)
            {
                <div class="form-group">
                    @Html.CheckBox(cat.Name,Model.BikeCategories.Count(x=>x.CategoryId==cat.Id)>0)
                    @Html.Label(cat.Name)
                </div>
            }
            <div class="form-group">
                <input type="submit" value="Save categories" class="btn btn-primary" />
            </div>
        </form>

    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Bikes/Views/AdminBike/Index.cshtml
@model IEnumerable<Bike>

@{
    ViewData["Title"] = "Index";
}

<h1>Bike list</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                Image Name
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                Categories
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Active)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @try
                    {
                        var image = item.BikeImages.FirstOrDefault(x => x.IsMainImage == true);
                        if (image != null)
                        {
                            <img src="@image.FileName" alt="@item.Name" height="100" />
                        }
                        else
                        {
                            <img src="~/images/noimage.jpg" alt="@item.Name" height="100" />
                        }
                    }
                    catch
                    {
                       <img src="~/images/noimage.jpg" alt="@item.Name" height="100" />
                    }


                </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
                <td>
                    @foreach (var category in item.BikeCategories)
                    {
                        var cat = (ViewBag.Categories as List<Category>).FirstOrDefault(x => x.Id == category.CategoryId);
                        <span>@cat.Name</span>

                        <br />
                    }
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.Active)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>