Bikes/Controllers/AdminOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Bikes.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Movies2.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminOrderController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AdminOrderController(ApplicationDbContext context)
        {
            _context = context;
        }
        private List<OrderItem> ItemsForOrder(int orderid)
        {
            return (
                from order_item in _context.OrderItem
                where order_item.OrderId == orderid
                select new OrderItem
                {
                    Id = order_item.Id,
                    OrderId = order_item.OrderId,
                    BikeId = order_item.BikeId,
                    Quantity = order_item.Quantity,
                    Price = order_item.Price,
                    BikeName = (from product in _context.Bike
                                where product.Id == order_item.BikeId
                                select product.Name).FirstOrDefault()



                }
                ).ToList();
        }
        // GET: AdminOrder
        public async Task<IActionResult> Index()
        {
            return _context.Order != null ?
                        View(await _context.Order.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Order'  is null.");
        }

        // GET: AdminOrder/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Order == null)
            {
                return NotFound();
            }

            var order = await _context.Order
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }
            order.OrderItems = ItemsForOrder((int)id);
            return View(order);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,DateCreated,Total,BillingFirstName,BillingLastName,BillingEmail,BillingPhone,BillingAddress,BillingCity,BillingPostalCode,BillingCountry,ShipppingFirstName,ShipppingLastName,SipppingEmail,SipppingPhoneNumber,SipppingAddress,SipppingCity,SipppingPostalCode,SipppingCountry,Message,UserId")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(order);
        }

        // GET: AdminOrder/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Order == null)
            {
                return NotFound();
            }

            var order = await _context.Order.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            order.OrderItems = ItemsForOrder((int)id);
            return View(order);
        }

        // POST: AdminOrder/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DateCreated,Total,BillingFirstName,BillingLastName,BillingEmail,BillingPhone,BillingAddress,BillingCity,BillingPostalCode,BillingCountry,ShipppingFirstName,ShipppingLastName,SipppingEmail,SipppingPhoneNumber,SipppingAddress,SipppingCity,SipppingPostalCode,SipppingCountry,Message,UserId")] Order order)
        {
            if (id != order.Id)
            {
                return NotFound();
            }
            ModelState.Remove("OrderItems");
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            order.OrderItems = ItemsForOrder((int)id);
            return View(order);
        }

        // GET: AdminOrder/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Order == null)
            {
                return NotFound();
            }

            var order = await _context.Order
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }
            order.OrderItems = ItemsForOrder((int)id);
            return View(order);
        }

        // POST: AdminOrder/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Order == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Order'  is null.");
            }
            var order = await _context.Order.FindAsync(id);
            if (order != null)
            {
                foreach (var orderItem in _context.OrderItem.Where(oi => oi.OrderId == order.Id))

                {
                    _context.Bike.Find(orderItem.BikeId).Quantity += orderItem.Quantity;
                    _context.OrderItem.Remove(orderItem);
                }
                _context.Order.Remove(order);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
            return (_context.Order?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Bikes/Controllers/AdminOrderItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Bikes.Models;

namespace Movies2.Controllers
{
    [Authorize(Roles = "Admin")]

    public class AdminOrderItemController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AdminOrderItemController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: AdminOrderItem
        public async Task<IActionResult> Index(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("index", "AdminOrder");
            }
            var orderItems = await _context.OrderItem.Where(o => o.OrderId == id).ToListAsync();
            foreach (var item in orderItems)
            {
                item.BikeName = (from bike in _context.Bike
                                     where bike.Id == item.BikeId
                                     select bike.Name).FirstOrDefault();


            }
            return View(orderItems);
        }
        // GET: AdminOrderItem/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.OrderItem == null)
            {
                return NotFound();
            }

            var orderItem = await _context.OrderItem
                .FirstOrDefaultAsync(m => m.Id == id);
            if (orderItem == null)
            {
                return NotFound();
            }
            orderItem.BikeName= (from bike in _context.Bike
                                      where bike.Id == orderItem.BikeId
                                      select bike.Name).FirstOrDefault();

            return View(orderItem);
        }

        // GET: AdminOrderItem/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: AdminOrderItem/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,OrderId,BikeId,Quantity,Price")] OrderItem orderItem)
        {
            if (ModelState.IsValid)
            {
                _context.Add(orderItem);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(orderItem);
        }

        // GET: AdminOrderItem/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.OrderItem == null)
            {
                return NotFound();
            }

            var orderItem = await _context.OrderItem.FindAsync(id);
            if (orderItem == null)
            {
                return NotFound();
            }
            orderItem.BikeName = (from bike in _context.Bike
                                      where bike.Id == orderItem.BikeId
                                      select bike.Name).FirstOrDefault();
            return View(orderItem);
        }

        // POST: AdminOrderItem/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,OrderId,BikeId,Quantity,Price")] OrderItem orderItem)
        {
            if (id != orderItem.Id)
            {
                return NotFound();
            }
            if (orderItem.Price <= 0)
            {
                ModelState.AddModelError("Price", " price must be greater than 0");
            }
            if (orderItem.Quantity <= 0)
            {
                ModelState.AddModelError("Qunatity", " Qunatity must be greater than 0");
            }
            ModelState.Remove("BikeName");
            if (ModelState.IsValid)
            {
                try
                {
                    var old_orderItem = await _context.OrderItem.FindAsync(id);
                    var quantity_diff = orderItem.Quantity - old_orderItem.Quantity;
                    var price_diff = orderItem.Price - old_orderItem.Price;
                    if (quantity_diff < 0)
                    {
                        _context.Bike.Find(orderItem.BikeId).Quantity += Math.Abs(quantity_diff);
                    }
                    if (quantity_diff > 0)
                    {
                        var availabile_quantity = _context.Bike.Find(orderItem.BikeId).Quantity;
                        if (availabile_quantity < quantity_diff)
                        {
                            ModelState.AddModelError("Quantity", $"Only {availabile_quantity} " +
                                $"items are available,you tried to add {quantity_diff}");
                            orderItem.BikeName = (from bike in _context.Bike
                                                      where bike.Id == orderItem.BikeId
                                                      select bike.Name).FirstOrDefault();
                            return View(orderItem);
                        }
                        _context.Bike.Find(orderItem.BikeId).Quantity -= quantity_diff;

                    }
                    if (price_diff != 0 || quantity_diff != 0)
                    {
                        var oldprice = old_orderItem.Price * old_orderItem.Quantity;
                        var new_price = orderItem.Price * orderItem.Quantity;


                        _context.Order.Find(orderItem.OrderId).Total += new_price - oldprice;

                    }
                    old_orderItem.Quantity = orderItem.Quantity;
                    old_orderItem.Price = orderItem.Price;
                    // _context.Update(orderItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderItemExists(orderItem.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { id = orderItem.OrderId });
            }
            orderItem.BikeName = (from bike in _context.Bike
                                  where bike.Id == orderItem.BikeId
                                  select bike.Name).FirstOrDefault();
            return View(orderItem);
        }

        // GET: AdminOrderItem/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.OrderItem == null)
            {
                return NotFound();
            }

            var orderItem = await _context.OrderItem
                .FirstOrDefaultAsync(m => m.Id == id);
            if (orderItem == null)
            {
                return NotFound();
            }
            orderItem.BikeName = (from Bike in _context.Bike
                                      where Bike.Id == orderItem.BikeId
                                      select Bike.Name).FirstOrDefault();
            return View(orderItem);
        }

        // POST: AdminOrderItem/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.OrderItem == null)
            {
                return Problem("Entity set 'ApplicationDbContext.OrderItem'  is null.");
            }
            var orderItem = await _context.OrderItem.FindAsync(id);
            int? orderid = orderItem.OrderId;
            if (orderItem != null)
            {
                _context.Bike.Find(orderItem.BikeId).Quantity += orderItem.Quantity;
                _context.Order.Find(orderItem.OrderId).Total -= orderItem.Price * orderItem.Quantity;
                _context.OrderItem.Remove(orderItem);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { id = orderid });



        }
        bool OrderItemExists(int id)
        {
            return (_context.OrderItem?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Bikes/Views/AdminOrder/Create.cshtml
@model Order

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DateCreated" class="control-label"></label>
                <input asp-for="DateCreated" class="form-control" />
                <span asp-validation-for="DateCreated" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Total" class="control-label"></label>
                <input asp-for="Total" class="form-control" />
                <span asp-validation-for="Total" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BillingFirstName" class="control-label"></label>
                <input asp-for="BillingFirstName" class="form-control" />
                <span asp-validation-for="BillingFirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BillingLastName" class="control-label"></label>
                <input asp-for="BillingLastName" class="form-control" />
                <span asp-validation-for="BillingLastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BillingEmail" class="control-label"></label>
                <input asp-for="BillingEmail" class="form-control" />
                <span asp-validation-for="BillingEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BillingPhone" class="control-label"></label>
                <input asp-for="BillingPhone" class="form-control" />
                <span asp-validation-for="BillingPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BillingAddress" class="control-label"></label>
                <input asp-for="BillingAddress" class="form-control" />
                <span asp-validation-for="BillingAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BillingCity" class="control-label"></label>
                <input asp-for="BillingCity" class="form-control" />
                <span asp-validation-for="BillingCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BillingPostalCode" class="control-label"></label>
                <input asp-for="BillingPostalCode" class="form-control" />
                <span asp-validation-for="BillingPostalCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BillingCountry" class="control-label"></label>
                <input asp-for="BillingCountry" class="form-control" />
                <span asp-validation-for="BillingCountry" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShipppingFirstName" class="control-label"></label>
                <input asp-for="ShipppingFirstName" class="form-control" />
                <span asp-validation-for="ShipppingFirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShipppingLastName" class="control-label"></label>
                <input asp-for="ShipppingLastName" class="form-control" />
                <span asp-validation-for="ShipppingLastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SipppingEmail" class="control-label"></label>
                <input asp-for="SipppingEmail" class="form-control" />
                <span asp-validation-for="SipppingEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SipppingPhoneNumber" class="control-label"></label>
                <input asp-for="SipppingPhoneNumber" class="form-control" />
                <span asp-validation-for="SipppingPhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SipppingAddress" class="control-label"></label>
                <input asp-for="SipppingAddress" class="form-control" />
                <span asp-validation-for="SipppingAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SipppingCity" class="control-label"></label>
                <input asp-for="SipppingCity" class="form-control" />
                <span asp-validation-for="SipppingCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SipppingPostalCode" class="control-label"></label>
                <input asp-for="SipppingPostalCode" class="form-control" />
                <span asp-validation-for="SipppingPostalCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SipppingCountry" class="control-label"></label>
                <input asp-for="SipppingCountry" class="form-control" />
                <span asp-validation-for="SipppingCountry" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Message" class="control-label"></label>
                <input asp-for="Message" class="form-control" />
                <span asp-validation-for="Message" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class="form-control" asp-items="ViewBag.UserId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Bikes/Views/AdminOrder/Details.cshtml
@model Order

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Order no. @Model.Id.ToString()</h4>
    <hr />
    <table class="table">
        <thead>
            <tr>
                <th scope="col">     @Html.DisplayNameFor(model => model.BillingFirstName)</th>
                <th scope="col">   @Html.DisplayNameFor(model => model.BillingLastName) </th>
                <th scope="col"> @Html.DisplayNameFor(model => model.BillingEmail) </th>
                <th scope="col"> @Html.DisplayNameFor(model => model.BillingPhone)  </th>
                <th scope="col"> @Html.DisplayNameFor(model => model.BillingAddress) </th>
                <th scope="col"> @Html.DisplayNameFor(model => model.BillingCity) </th>
                <th scope="col">  @Html.DisplayNameFor(model => model.BillingPostalCode) </th>
                <th scope="col"> @Html.DisplayNameFor(model => model.BillingCountry)</th>

            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Html.DisplayFor(model => model.BillingFirstName) </td>
                <td>@Html.DisplayFor(model => model.BillingLastName)</td>
                <td> @Html.DisplayFor(model => model.BillingEmail)</td>
                <td> @Html.DisplayFor(model => model.BillingPhone)</td>
                <td> @Html.DisplayFor(model => model.BillingAddress)</td>
                <td> @Html.DisplayFor(model => model.BillingCity)</td>
                <td> @Html.DisplayFor(model => model.BillingPostalCode)</td>
                <td> @Html.DisplayFor(model => model.BillingCountry)</td>
            </tr>
        </tbody>
    </table>
    <hr />
    <table class="table">
        <thead>
            <tr>
                <th scope="col">     @Html.DisplayNameFor(model => model.ShipppingFirstName)</th>
                <th scope="col">   @Html.DisplayNameFor(model => model.ShipppingLastName) </th>
                <th scope="col"> @Html.DisplayNameFor(model => model.SipppingEmail) </th>
                <th scope="col"> @Html.DisplayNameFor(model => model.SipppingPhoneNumber)  </th>
                <th scope="col"> @Html.DisplayNameFor(model => model.SipppingAddress) </th>
                <th scope="col"> @Html.DisplayNameFor(model => model.SipppingCity) </th>
                <th scope="col">  @Html.DisplayNameFor(model => model.SipppingPostalCode) </th>
                <th scope="col"> @Html.DisplayNameFor(model => model.SipppingCountry)</th>

            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Html.DisplayFor(model => model.ShipppingFirstName) </td>
                <td>@Html.DisplayFor(model => model.ShipppingLastName)</td>
                <td> @Html.DisplayFor(model => model.SipppingEmail)</td>
                <td> @Html.DisplayFor(model => model.SipppingPhoneNumber)</td>
                <td> @Html.DisplayFor(model => model.SipppingAddress)</td>
                <td> @Html.DisplayFor(model => model.SipppingCity)</td>
                <td> @Html.DisplayFor(model => model.SipppingPostalCode)</td>
                <td> @Html.DisplayFor(model => model.SipppingCountry)</td>
            </tr>
        </tbody>
    </table>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Total)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Total) €
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Message)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Message)
        </dd>
    </dl>
    <partial name="_OrderItemsPartial" for="@Model.OrderItems" />

</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Bikes/Views/AdminOrder/Edit.cshtml
@model Order

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Order no.@Model.Id</h4>
<h5>Created on @Model.DateCreated.ToString("yyyy-MM-dd")</h5>
<hr />
<div class="row">
    <form asp-action="Edit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="Total" />
        <input type="hidden" asp-for="UserId" />
        <input type="hidden" asp-for="DateCreated" />
        <table class="table">
            <thead>
                <tr>
                    <th scope="col"><label asp-for="BillingFirstName" class="control-label"></label></th>
                    <th scope="col"><label asp-for="BillingLastName" class="control-label"></label></th>
                    <th scope="col"><label asp-for="BillingEmail" class="control-label"></label></th>
                    <th scope="col"><label asp-for="BillingPhone" class="control-label"></label></th>
                    <th scope="col"><label asp-for="BillingAddress" class="control-label"></label></th>
                    <th scope="col"><label asp-for="BillingCity" class="control-label"></label></th>
                    <th scope="col"><label asp-for="BillingPostalCode" class="control-label"></label></th>
                    <th scope="col"><label asp-for="BillingCountry" class="control-label"></label></th>
                </tr>
            </thead>
            <tbody>
            <td>
                <input asp-for="BillingFirstName" class="form-control" />
                <span asp-validation-for="BillingFirstName" class="text-danger"></span>
            </td>
            <td>
                <input asp-for="BillingLastName" class="form-control" />
                <span asp-validation-for="BillingLastName" class="text-danger"></span>
            </td>
            <td>
                <input asp-for="BillingEmail" class="form-control" />
                <span asp-validation-for="BillingEmail" class="text-danger"></span>
            </td>
            <td>
                <input asp-for="BillingPhone" class="form-control" />
                <span asp-validation-for="BillingPhone" class="text-danger"></span>
            </td>
            <td>
                <input asp-for="BillingAddress" class="form-control" />
                <span asp-validation-for="BillingAddress" class="text-danger"></span>
            </td>
            <td>
                <input asp-for="BillingCity" class="form-control" />
                <span asp-validation-for="BillingCity" class="text-danger"></span>
            </td>
            <td>
                <input asp-for="BillingPostalCode" class="form-control" />
                <span asp-validation-for="BillingPostalCode" class="text-danger"></span>
            </td>
            <td>
                <input asp-for="BillingCountry" class="form-control" />
                <span asp-validation-for="BillingCountry" class="text-danger"></span>
            </td>
            </tbody>
        </table>
        <hr />
        <table class="table">
            <thead>
                <tr>
                    <th scope="col"><label asp-for="ShipppingFirstName" class="control-label"></label></th>
                    <th scope="col"><label asp-for="ShipppingLastName" class="control-label"></label></th>
                    <th scope="col"><label asp-for="SipppingEmail" class="control-label"></label></th>
                    <th scope="col"><label asp-for="SipppingPhoneNumber" class="control-label"></label></th>
                    <th scope="col"><label asp-for="SipppingAddress" class="control-label"></label></th>
                    <th scope="col"><label asp-for="SipppingCity" class="control-label"></label></th>
                    <th scope="col"><label asp-for="SipppingPostalCode" class="control-label"></label></th>
                    <th scope="col"><label asp-for="SipppingCountry" class="control-label"></label></th>
                </tr>
            </thead>
            <tbody>
            <td>
                <input asp-for="ShipppingFirstName" class="form-control" />
                <span asp-validation-for="ShipppingFirstName" class="text-danger"></span>
            </td>
            <td>
                <input asp-for="ShipppingLastName" class="form-control" />
                <span asp-validation-for="ShipppingLastName" class="text-danger"></span>
            </td>
            <td>
                <input asp-for="SipppingEmail" class="form-control" />
                <span asp-validation-for="SipppingEmail" class="text-danger"></span>
            </td>
            <td>
                <input asp-for="SipppingPhoneNumber" class="form-control" />
                <span asp-validation-for="SipppingPhoneNumber" class="text-danger"></span>
            </td>
            <td>
                <input asp-for="SipppingAddress" class="form-control" />
                <span asp-validation-for="SipppingAddress" class="text-danger"></span>
            </td>
            <td>
                <input asp-for="SipppingCity" class="form-control" />
                <span asp-validation-for="SipppingCity" class="text-danger"></span>
            </td>
            <td>
                <input asp-for="SipppingPostalCode" class="form-control" />
                <span asp-validation-for="SipppingPostalCode" class="text-danger"></span>
            </td>
            <td>
                <input asp-for="SipppingCountry" class="form-control" />
                <span asp-validation-for="SipppingCountry" class="text-danger"></span>
                <span asp-validation-for="SipppingCountry" class="text-danger"></span>
            </td>
            </tbody>
        </table>
        <div class="form-group">
            <label asp-for="Message" class="control-label"></label>
            <textarea asp-for="Message" class="form-control" rows="5"></textarea>
            <span asp-validation-for="Message" class="text-danger"></span>
        </div>

        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>
    </form>
</div>
<br />

<hr />

<a asp-action="Index" asp-controller="AdminOrderItem" asp-route-id="@Model.Id">Edit order items</a>
<partial name="_OrderItemsPartial" for="@Model.OrderItems" />
<div>
    <a asp-action="Index">Back to List</a>
</div>